Changed Exception to Throwable so it'll catch NoClassDefFoundError too.
git-svn-id: https://stripes.svn.sourceforge.net/svnroot/stripes/trunk@795 d471f07e-d8fc-0310-a67b-dd4c8ff0e7cd